name: Hexo Auto Build & Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

env:
  NODE_VERSION: 'lts/*'
  BUILD_TIME: ${{ github.event.head_commit.timestamp }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.28.0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Show Platform Info
        run: |
          echo "Node.js: $(node -v)"
          echo "npm: $(npm -v)"
          echo "Ubuntu: $(cat /etc/lsb-release | grep DESCRIPTION)"

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Generate
        run: pnpm exec hexo clean && pnpm exec hexo generate

      - name: Deploy to public branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: public
          force_orphan: true
          full_commit_message: 'Deploy from ${{ github.sha }}'


